[#ftl]

[#include '/ftl/libs/kindEditor.ftl']
[#include '/ftl/libs/bodynt.ftl']
[#include '/ftl/libs/editbackbutton.ftl']
[#include '/ftl/libs/head_nt.ftl']
[#include '/ftl/libs/submit.ftl']
[#include '/ftl/libs/imgUploadSmallBig.ftl']
[#include '/ftl/libs/input.ftl']
[#include '/ftl/libs/textarea.ftl']
[#include '/ftl/libs/head_list.ftl']
[#include '/ftl/libs/body_list.ftl']
[#include '/ftl/libs/checkbox.ftl']
[#include '/ftl/libs/dorder.ftl']
[#include '/ftl/libs/photowall.ftl']
[#include '/ftl/libs/singlephoto.ftl']
[#include '/ftl/libs/textSearchLabel.ftl']
[#include '/ftl/libs/search.ftl']
[#include '/ftl/libs/datetime.ftl']
[#include '/ftl/libs/select.ftl']